# Discovery Server Access
eureka:
  client:
    service-url:
      defaultZone: http://annuaire:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30


management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - beans
        - health
        - metrics
        - httptrace
        - mappings
        - refresh
        - info
        - routes
        - hystrix.stream
  endpoint:
    health:
      show-details: always
      
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

